### Case 1
#### 1) The Dev Team was tired of developing the same old queries just varying the filters accordingly to their boss demands.
As a new member of the crew, your mission now is to create a dynamic function in Python, on the most flexible of ways, to produce queries and retrieve a dataframe based on three parameters:

- product_code: integer

- store_code: integer

- date: list of ISO-like strings

- Date e.g.
  - ['2019-01-01', '2019-01-31']

It should look like this
my_data = retrieve_data(product_code, store_code, date)

Make your team proud!

Extra instructions:
- Retrieve all columns from table data_product_sales;
- Imagine people from other teams will also utilize this function!

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
def retrieve_data(product_code, store_code, date):
    # 1. Credenciais de acesso
    usuario = 'looqbox-challenge'
    senha = 'looq-challenge'
    host = '35.199.115.174'
    porta = '3306'          # porta padrão do MySQL
    nome_do_banco = 'looqbox-challenge'

    # 2. String de conexão (URL de conexão)
    # Formato: mysql+pymysql://usuario:senha@host:porta/nome_do_banco
    string_conexao = f'mysql+pymysql://{usuario}:{senha}@{host}:{porta}/{nome_do_banco}'

    # 3. Motor de conexão (engine)
    engine = create_engine(string_conexao)

    # 4. Consulta SQL
    query = """SELECT * FROM `looqbox-challenge`.`data_product_sales`
            WHERE PRODUCT_CODE = %s
            AND DATE BETWEEN %s AND %s
            AND STORE_CODE = %s"""

    df = pd.read_sql(query, con=engine, params=(product_code, date[0], date[1], store_code))

    # 6. retorna o DataFrame
    return df

  STORE_CODE  PRODUCT_CODE        DATE  SALES_VALUE  SALES_QTY
0          1            18  2019-01-01        708.5       65.0
1          1            18  2019-01-02       1297.1      119.0
2          1            18  2019-01-03       1144.5      105.0
3          1            18  2019-01-04       1090.0      100.0
4          1            18  2019-01-05        893.8       82.0

In [20]:
my_data = retrieve_data(product_code=18, store_code=1, date=['2019-01-01', '2019-03-31'])
my_data

   STORE_CODE  PRODUCT_CODE        DATE  SALES_VALUE  SALES_QTY
0           1            18  2019-01-01        708.5       65.0
1           1            18  2019-01-02       1297.1      119.0
2           1            18  2019-01-03       1144.5      105.0
3           1            18  2019-01-04       1090.0      100.0
4           1            18  2019-01-05        893.8       82.0
..        ...           ...         ...          ...        ...
85          1            18  2019-03-27       1308.0      120.0
86          1            18  2019-03-28       1079.1       99.0
87          1            18  2019-03-29       1002.8       92.0
88          1            18  2019-03-30        741.2       68.0
89          1            18  2019-03-31        741.2       68.0

[90 rows x 5 columns]